#
#	# before
#	try
#
#	# after
#	try{
#		|
#	}catch(const std::exception&){
#		
#	}
#
# --
try{
	%|
}catch(const std::exception&){
	
}